### ISSUE TITLE
Development enviroment not working on Mac since v1.4.0. 

### ISSUE THREAD

**Issue by chengzhuzhang** [E3SM-Project/e3sm_diags#200]
Should look into this.

**Comment by zshaheen** [comment]
When running `conda build conda/ -c conda-forge -c cdat` on mac, the following error is displayed:
```
Traceback (most recent call last):
  File "/Users/shaheen2/anaconda2/bin/conda-build", line 11, in <module>
    sys.exit(main())
  File "/Users/shaheen2/anaconda2/lib/python2.7/site-packages/conda_build/cli/main_build.py", line 456, in main
    execute(sys.argv[1:])
  File "/Users/shaheen2/anaconda2/lib/python2.7/site-packages/conda_build/cli/main_build.py", line 447, in execute
    verify=args.verify, variants=args.variants)
  File "/Users/shaheen2/anaconda2/lib/python2.7/site-packages/conda_build/api.py", line 208, in build
    notest=notest, need_source_download=need_source_download, variants=variants)
  File "/Users/shaheen2/anaconda2/lib/python2.7/site-packages/conda_build/build.py", line 2314, in build_tree
    notest=notest,
  File "/Users/shaheen2/anaconda2/lib/python2.7/site-packages/conda_build/build.py", line 1397, in build
    create_build_envs(m, notest)
  File "/Users/shaheen2/anaconda2/lib/python2.7/site-packages/conda_build/build.py", line 1281, in create_build_envs
    raise e
conda_build.exceptions.DependencyNeedsBuildingError: Unsatisfiable dependencies for platform osx-64: set(['*[track_features=debug]', 'python=3.6'])
```

**Comment by zshaheen** [comment]
It seems like there's a dependency that doesn't work with Python 3.6 on mac. So we're able to create Python 2.6 envs of this software.

**Comment by zshaheen** [comment]
[Please see this comment.](https://github.com/E3SM-Project/e3sm_diags/issues/207#issuecomment-498349914)
