### ISSUE TITLE
PSL missing from reference data

### ISSUE THREAD

**Issue by sterlingbaldwin** [E3SM-Project/e3sm_diags#211]
I was just running a test case on cori, and the following errors were in the output. Am I using the wrong input data?

```
Error in acme_diags.driver.lat_lon_driver
Traceback (most recent call last):
  File "/global/project/projectdirs/acme/software/anaconda_envs/edison/base/envs/e3sm_unified_1.2.3_py2.7_nox/lib/python2.7/site-packages/e3sm_diags-1.4.0-py2.7.egg-info/scripts/acme_diags_driver.py", line 183, in run_diag
    single_result = module.run_diag(parameters)
  File "/global/project/projectdirs/acme/software/anaconda_envs/edison/base/envs/e3sm_unified_1.2.3_py2.7_nox/lib/python2.7/site-packages/acme_diags/driver/lat_lon_driver.py", line 108, in run_diag
    var, acme.derived_variables, f_obs, parameter)
  File "/global/project/projectdirs/acme/software/anaconda_envs/edison/base/envs/e3sm_unified_1.2.3_py2.7_nox/lib/python2.7/site-packages/acme_diags/derivations/acme.py", line 16, in process_derived_var
    return _compute_derived_var(var_key, derived_vars_dict, nc_file)
  File "/global/project/projectdirs/acme/software/anaconda_envs/edison/base/envs/e3sm_unified_1.2.3_py2.7_nox/lib/python2.7/site-packages/acme_diags/derivations/acme.py", line 64, in _compute_derived_var
    derived_var_inputs, nc_file.id))
RuntimeError: None of the variables ([('PSL',), ('psl',)]) are in the file: /global/project/projectdirs/acme/acme_diags/obs_for_acme_diags/MERRA2_JJA_1980-2016_climo.nc
test file: /global/cscratch1/sd/sbaldwin/1pct/output/temp/1pct/e3sm_diags/0001_0001_vs_obs/20180215.DECKv1b_1pctCO2.ne30_oEC.edison_SON_000109_000111_climo.nc
reference file: /global/project/projectdirs/acme/acme_diags/obs_for_acme_diags/MERRA2_SON_1980-2016_climo.nc
```

**Comment by zshaheen** [comment]
@sterlingbaldwin, it seems like there aren't any variables (`PSL` or `psl`) in the file `/global/project/projectdirs/acme/acme_diags/obs_for_acme_diags/MERRA2_JJA_1980-2016_climo.nc`. I've checked with `ncdump` and they **do not** seem to be there. So it looks like the software is working as expected.

Also, you're running an older version of `e3sm_diags`, v1.4.0. If you're using v1.6.0 or later, I'd use the path below ('obs_for_e3sm_diags', not 'acme_diags') for the observational data.
```
/global/project/projectdirs/acme/acme_diags/obs_for_e3sm_diags/
```

**Comment by sterlingbaldwin** [comment]
All the tools that processflow runs source the e3sm-unified environment and use whatever version is available there. It looks like the older version doesnt know how to find the files in the ```/global/project/projectdirs/acme/acme_diags/obs_for_e3sm_diags``` directory.

**Comment by zshaheen** [comment]
Yes, you are correct. The new directory you linked only works with v1.6.0 or greater of e3sm_diags. 

Since you're on Shifter, you can use the container for v1.6.0 to run it if you want to. No downloading is needed, since it's already downloaded in the shared location. Just wget the `e3sm_diags_container.py` script and replace every instance of `e3sm_diags` with `python e3sm_diags_container.py --shifter`.

[The full guide is here if you're interested](https://e3sm-project.github.io/e3sm_diags/docs/html/quickguides/quick-guide-cori.html).
