### ISSUE TITLE
Can't have `import` in the parameter files

### ISSUE THREAD

**Issue by zshaheen** [E3SM-Project/e3sm_diags#226]
When we try to have an `import` statement in the Python input file, we get the error below.
```
Traceback (most recent call last):
  File "/global/homes/z/zshaheen/anaconda2/envs/e3sm_diags_py3_try2/bin/e3sm_diags", line 10, in <module>
    sys.exit(main())
  File "/global/homes/z/zshaheen/anaconda2/envs/e3sm_diags_py3_try2/lib/python3.6/site-packages/acme_diags/acme_diags_driver.py", line 223, in main
    parameters = get_parameters(parser)
  File "/global/homes/z/zshaheen/anaconda2/envs/e3sm_diags_py3_try2/lib/python3.6/site-packages/acme_diags/acme_diags_driver.py", line 186, in get_parameters
    parameters = parser.get_parameters(cmd_default_vars=False, argparse_vals_only=False)
  File "/global/homes/z/zshaheen/anaconda2/envs/e3sm_diags_py3_try2/lib/python3.6/site-packages/cdp-1.4.2-py3.6.egg/cdp/cdp_parser.py", line 526, in get_parameters
    final_parameters = self.granulate(final_parameters)
  File "/global/homes/z/zshaheen/anaconda2/envs/e3sm_diags_py3_try2/lib/python3.6/site-packages/cdp-1.4.2-py3.6.egg/cdp/cdp_parser.py", line 394, in granulate
    for var_name, var_value in attrs:
RuntimeError: dictionary changed size during iteration
```

When we turn off the feature to granularize the parameters by putting `granulate = []` in the Python file, all works fine.

**Comment by zshaheen** [comment]
In [v1.5.1 of `cdp`](https://github.com/CDAT/cdp/releases/tag/v1.5.1), we can now import modules in the Python parameter files.

Specially, to get numpy arrays working, we had to have more fixes. These were done in 9e31d3a01e13af9cba4a57226a7535212298d88c. As expected, when using `numpy.ndarrays`, we don't have the parameter, `zonal_mean_2d_plevs` in this case, as a command line parameter. Serializing an object of that type is not straightforward.

---

So @oksanaguba and @chengzhuzhang, if you want to be able to use set `zonal_mean_2d_plevs` to a numpy array in the Python parameter files, please use the latest code on master and update to v1.5.1 of cdp.

Below is a modified version of the parameter file used in the system tests and it's respective output:
```python
# all_sets.py
import numpy

reference_data_path = '.'
test_data_path = '.'
results_dir = 'all_sets_results'

zonal_mean_2d_plevs = numpy.logspace(2.0, 3.0, num=3)
```

![ERA-Interim-T-ANN-global](https://user-images.githubusercontent.com/4239938/59068780-f97a5b80-8869-11e9-9a44-15a78a9b9416.png)
