### ISSUE TITLE
TypeError: cannot deepcopy this pattern object

### ISSUE THREAD

**Issue by chengzhuzhang** [E3SM-Project/e3sm_diags#245]
Running into this error when testing one run configuration. I tried to run the same script (using API) in serial, interactive session and using batch script. It only occurs when running by submitting as a batch job. Seems like a random thing. Need to investigate further

```
Traceback (most recent call last):
  File "/qfs/people/zhan429/.conda/envs/e3sm_diags_env_dev_1.7.1/bin/e3sm_diags", line 10, in <module>
    sys.exit(main())
  File "/qfs/people/zhan429/.conda/envs/e3sm_diags_env_dev_1.7.1/lib/python3.6/site-packages/acme_diags/acme_diags_driver.py", line 290, in main
    parameters = get_parameters(parser)
  File "/qfs/people/zhan429/.conda/envs/e3sm_diags_env_dev_1.7.1/lib/python3.6/site-packages/acme_diags/acme_diags_driver.py", line 249, in get_parameters
    other_parameters=other_parameters, cmd_default_vars=False, argparse_vals_only=False)
  File "/qfs/people/zhan429/.conda/envs/e3sm_diags_env_dev_1.7.1/lib/python3.6/site-packages/cdp/cdp_parser.py", line 532, in get_parameters
    final_parameters = self.granulate(final_parameters)
  File "/qfs/people/zhan429/.conda/envs/e3sm_diags_env_dev_1.7.1/lib/python3.6/site-packages/cdp/cdp_parser.py", line 418, in granulate
    p = copy.deepcopy(param)
  File "/qfs/people/zhan429/.conda/envs/e3sm_diags_env_dev_1.7.1/lib/python3.6/copy.py", line 180, in deepcopy
    y = _reconstruct(x, memo, *rv)
  File "/qfs/people/zhan429/.conda/envs/e3sm_diags_env_dev_1.7.1/lib/python3.6/copy.py", line 280, in _reconstruct
    state = deepcopy(state, memo)
  File "/qfs/people/zhan429/.conda/envs/e3sm_diags_env_dev_1.7.1/lib/python3.6/copy.py", line 150, in deepcopy
    y = copier(x, memo)
  File "/qfs/people/zhan429/.conda/envs/e3sm_diags_env_dev_1.7.1/lib/python3.6/copy.py", line 240, in _deepcopy_dict
    y[deepcopy(key, memo)] = deepcopy(value, memo)
  File "/qfs/people/zhan429/.conda/envs/e3sm_diags_env_dev_1.7.1/lib/python3.6/copy.py", line 180, in deepcopy
    y = _reconstruct(x, memo, *rv)
  File "/qfs/people/zhan429/.conda/envs/e3sm_diags_env_dev_1.7.1/lib/python3.6/copy.py", line 280, in _reconstruct
    state = deepcopy(state, memo)
  File "/qfs/people/zhan429/.conda/envs/e3sm_diags_env_dev_1.7.1/lib/python3.6/copy.py", line 150, in deepcopy
    y = copier(x, memo)
  File "/qfs/people/zhan429/.conda/envs/e3sm_diags_env_dev_1.7.1/lib/python3.6/copy.py", line 240, in _deepcopy_dict
    y[deepcopy(key, memo)] = deepcopy(value, memo)
  File "/qfs/people/zhan429/.conda/envs/e3sm_diags_env_dev_1.7.1/lib/python3.6/copy.py", line 180, in deepcopy
    y = _reconstruct(x, memo, *rv)
  File "/qfs/people/zhan429/.conda/envs/e3sm_diags_env_dev_1.7.1/lib/python3.6/copy.py", line 280, in _reconstruct
    state = deepcopy(state, memo)
  File "/qfs/people/zhan429/.conda/envs/e3sm_diags_env_dev_1.7.1/lib/python3.6/copy.py", line 150, in deepcopy
    y = copier(x, memo)
  File "/qfs/people/zhan429/.conda/envs/e3sm_diags_env_dev_1.7.1/lib/python3.6/copy.py", line 240, in _deepcopy_dict
    y[deepcopy(key, memo)] = deepcopy(value, memo)
  File "/qfs/people/zhan429/.conda/envs/e3sm_diags_env_dev_1.7.1/lib/python3.6/copy.py", line 150, in deepcopy
    y = copier(x, memo)
  File "/qfs/people/zhan429/.conda/envs/e3sm_diags_env_dev_1.7.1/lib/python3.6/copy.py", line 215, in _deepcopy_list
    append(deepcopy(a, memo))
  File "/qfs/people/zhan429/.conda/envs/e3sm_diags_env_dev_1.7.1/lib/python3.6/copy.py", line 180, in deepcopy
    y = _reconstruct(x, memo, *rv)
  File "/qfs/people/zhan429/.conda/envs/e3sm_diags_env_dev_1.7.1/lib/python3.6/copy.py", line 280, in _reconstruct
    state = deepcopy(state, memo)
  File "/qfs/people/zhan429/.conda/envs/e3sm_diags_env_dev_1.7.1/lib/python3.6/copy.py", line 150, in deepcopy
    y = copier(x, memo)
  File "/qfs/people/zhan429/.conda/envs/e3sm_diags_env_dev_1.7.1/lib/python3.6/copy.py", line 240, in _deepcopy_dict
    y[deepcopy(key, memo)] = deepcopy(value, memo)
  File "/qfs/people/zhan429/.conda/envs/e3sm_diags_env_dev_1.7.1/lib/python3.6/copy.py", line 180, in deepcopy
    y = _reconstruct(x, memo, *rv)
  File "/qfs/people/zhan429/.conda/envs/e3sm_diags_env_dev_1.7.1/lib/python3.6/copy.py", line 280, in _reconstruct
    state = deepcopy(state, memo)
  File "/qfs/people/zhan429/.conda/envs/e3sm_diags_env_dev_1.7.1/lib/python3.6/copy.py", line 150, in deepcopy
    y = copier(x, memo)
  File "/qfs/people/zhan429/.conda/envs/e3sm_diags_env_dev_1.7.1/lib/python3.6/copy.py", line 240, in _deepcopy_dict
    y[deepcopy(key, memo)] = deepcopy(value, memo)
  File "/qfs/people/zhan429/.conda/envs/e3sm_diags_env_dev_1.7.1/lib/python3.6/copy.py", line 161, in deepcopy
    y = copier(memo)
TypeError: cannot deepcopy this pattern object
```

**Comment by chengzhuzhang** [comment]
It seems like a one-time glitch on Cori. Close for now
