### ISSUE TITLE
Replace os.errno with errno for py3.7 

### ISSUE THREAD

**Issue by chengzhuzhang** [E3SM-Project/e3sm_diags#333]
os.errno is no longer supported moving on to py 3.7. Error message see below:
```
Traceback (most recent call last):
  File "/global/cfs/cdirs/e3sm/zhang40/conda_envs/e3sm_diag_mpi4py_nompi_py37/lib/python3.7/site-packages/acme_diags/acme_diags_driver.py", line 275, in run_diag
    single_result = module.run_diag(parameters)
  File "/global/cfs/cdirs/e3sm/zhang40/conda_envs/e3sm_diag_mpi4py_nompi_py37/lib/python3.7/site-packages/acme_diags/driver/lat_lon_driver.py", line 196, in run_diag
    parameter.current_set, parameter), parameter.output_file + '.json')
  File "/global/cfs/cdirs/e3sm/zhang40/conda_envs/e3sm_diag_mpi4py_nompi_py37/lib/python3.7/site-packages/acme_diags/driver/utils/general.py", line 310, in get_output_dir
    if e.errno != os.errno.EEXIST:
AttributeError: module 'os' has no attribute 'errno'
```
Suggested Solution following: https://github.com/Qiskit/qiskit-terra/issues/1253:
 Replacing os.errno by just errno (after having imported it).

**Comment by chengzhuzhang** [comment]
fixed in https://github.com/E3SM-Project/e3sm_diags/pull/334
