### ISSUE TITLE
Error when running quick start for Cori

### ISSUE THREAD

**Issue by xylar** [E3SM-Project/e3sm_diags#338]
I'm running with the current `master` on Cori.  I copied and pasted the example `run_e3sm_diags.py` from here:
https://e3sm-project.github.io/e3sm_diags/docs/html/quickguides/quick-guide-cori.html#config-and-run

When I run, most things work but I see:
```
No 'yrs_averaged' exists in the global attributes.
Variable: SST
Error in acme_diags.driver.lat_lon_driver
Traceback (most recent call last):
  File "/global/homes/x/xylar/miniconda3/envs/e3sm_diags_dev/lib/python3.7/site-packages/acme_diags/acme_diags_driver.py", line 275, in run_diag
    single_result = module.run_diag(parameters)
  File "/global/homes/x/xylar/miniconda3/envs/e3sm_diags_dev/lib/python3.7/site-packages/acme_diags/driver/lat_lon_driver.py", line 80, in run_diag
    mv2 = ref_data.get_climo_variable(var, season)
  File "/global/homes/x/xylar/miniconda3/envs/e3sm_diags_dev/lib/python3.7/site-packages/acme_diags/driver/utils/dataset.py", line 138, in get_climo_variable
    filename = self.get_ref_filename_climo(season)
  File "/global/homes/x/xylar/miniconda3/envs/e3sm_diags_dev/lib/python3.7/site-packages/acme_diags/driver/utils/dataset.py", line 256, in get_ref_filename_climo
    return self._get_climo_filename(path, data_name, season)
  File "/global/homes/x/xylar/miniconda3/envs/e3sm_diags_dev/lib/python3.7/site-packages/acme_diags/driver/utils/dataset.py", line 272, in _get_climo_filename
    raise IOError("No file found for {} and {} in {}".format(data_name, season, path))
OSError: No file found for HadISST and ANN in /global/cfs/cdirs/e3sm/acme_diags/obs_for_e3sm_diags/climatology/
```
Is there some new data needed for this example to work with the current release?

**Comment by xylar** [comment]
Also, the account name should be `e3sm` instead of `acme` in the example batch job:
```
...
#SBATCH --account=acme
```

**Comment by xylar** [comment]
I'm also sometimes seeing a weird keyboard interrupt error even though I'm pretty sure I didn't do anything:
```
OpenBLAS blas_thread_init: RLIMIT_NPROC 2048 current, 513048 max
Error in acme_diags.driver.lat_lon_driver
Traceback (most recent call last):
  File "/global/homes/x/xylar/miniconda3/envs/e3sm_diags_cdp_fork/lib/python3.7/site-packages/acme_diags/acme_diags_driver.py", line 275, in run_diag
    single_result = module.run_diag(parameters)
  File "/global/homes/x/xylar/miniconda3/envs/e3sm_diags_cdp_fork/lib/python3.7/site-packages/acme_diags/driver/lat_lon_driver.py", line 207, in run_diag
    mv1_domain, diff, metrics_dict, parameter)
  File "/global/homes/x/xylar/miniconda3/envs/e3sm_diags_cdp_fork/lib/python3.7/site-packages/acme_diags/plot/__init__.py", line 43, in plot
    plot_fcn(ref, test, diff, metrics_dict, parameter)
  File "/global/homes/x/xylar/miniconda3/envs/e3sm_diags_cdp_fork/lib/python3.7/site-packages/acme_diags/plot/cartopy/lat_lon_plot.py", line 207, in plot
    (parameter.test_name_yrs, parameter.test_title, test.units), parameter, stats=(max1, mean1, min1))
  File "/global/homes/x/xylar/miniconda3/envs/e3sm_diags_cdp_fork/lib/python3.7/site-packages/acme_diags/plot/cartopy/lat_lon_plot.py", line 122, in plot_panel
    extend='both',
  File "/global/homes/x/xylar/miniconda3/envs/e3sm_diags_cdp_fork/lib/python3.7/site-packages/cartopy/mpl/geoaxes.py", line 310, in wrapper
    return func(self, *args, **kwargs)
  File "/global/homes/x/xylar/miniconda3/envs/e3sm_diags_cdp_fork/lib/python3.7/site-packages/cartopy/mpl/geoaxes.py", line 1512, in contourf
    for col in result.collections
  File "/global/homes/x/xylar/miniconda3/envs/e3sm_diags_cdp_fork/lib/python3.7/site-packages/cartopy/mpl/geoaxes.py", line 1513, in <listcomp>
    if col.get_paths()]
  File "/global/homes/x/xylar/miniconda3/envs/e3sm_diags_cdp_fork/lib/python3.7/site-packages/matplotlib/collections.py", line 281, in get_datalim
    return result.transformed(transData.inverted())
  File "/global/homes/x/xylar/miniconda3/envs/e3sm_diags_cdp_fork/lib/python3.7/site-packages/matplotlib/transforms.py", line 2377, in inverted
    self._b.inverted(), self._a.inverted())
  File "/global/homes/x/xylar/miniconda3/envs/e3sm_diags_cdp_fork/lib/python3.7/site-packages/matplotlib/transforms.py", line 2377, in inverted
    self._b.inverted(), self._a.inverted())
  File "/global/homes/x/xylar/miniconda3/envs/e3sm_diags_cdp_fork/lib/python3.7/site-packages/matplotlib/transforms.py", line 1822, in inverted
    self._inverted = Affine2D(inv(mtx), shorthand_name=shorthand_name)
  File "<__array_function__ internals>", line 6, in inv
  File "/global/homes/x/xylar/miniconda3/envs/e3sm_diags_cdp_fork/lib/python3.7/site-packages/numpy/linalg/linalg.py", line 546, in inv
    ainv = _umath_linalg.inv(a, signature=signature, extobj=extobj)
KeyboardInterrupt
```

**Comment by chengzhuzhang** [comment]
Hi @xylar, 

The first error on `OSError: No file found for HadISST and ANN in /global/cfs/cdirs/e3sm/acme_diags/obs_for_e3sm_diags/climatology/` is expected. In the climo vs climo case, with HadISST climatology files we have pre-calcuated climatology for 3 time periods `HadISST_PD(present-day)`, `HadISST_PI (pre-industrial)` and `HadISST_CL(climatology over all available years)`.  In the case when using time-series data as input, and climatology are calculated on the fly, the program switch to use monthly time-series data from HadISST (`obs_for_e3sm_diags/time-series/HadISST`). This error won't appear in `time-series input` config. 

The `keyboard interrupt error` is new to me. I guess i will keep an eye one this. It would be best if we can figure out how to reproduce this error. 

Yes, we should replace the account from `acme` to `e3sm`. I didn't have chance to make the change. I have some more documentation change planned will update them soon.
