### ISSUE TITLE
test_streamflow failing

### ISSUE THREAD

**Issue by xylar** [E3SM-Project/e3sm_diags#363]
I don't think this is because of lack of local data but I could be wrong.  If it is, it would be good to separate tests that require downloading data from those that should work in CI (e.g. conda-forge feedstock).

```
+ bash tests/test.sh
/home/conda/feedstock_root/build_artifacts/e3sm_diags_1606894934352/_test_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_place/lib/python3.9/site-packages/cdutil-v3.0_40_g524a4f5-py3.6.egg/cdutil/region.py:140: UserWarning: Only axis bounds (min, max) can be specified for axis, other arguments are ignored.
/home/conda/feedstock_root/build_artifacts/e3sm_diags_1606894934352/_test_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_place/lib/python3.9/site-packages/acme_diags/driver/qbo_driver.py:77: RuntimeWarning: divide by zero encountered in true_divide
  period = 1 / frequency
/home/conda/feedstock_root/build_artifacts/e3sm_diags_1606894934352/_test_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_place/lib/python3.9/site-packages/acme_diags/driver/qbo_driver.py:81: ComplexWarning: Casting complex values to real discards the imaginary part
  psd_sumN[ilev] = 2 * np.nansum(fyy[(period <= 40) & (period >= 20)])
/home/conda/feedstock_root/build_artifacts/e3sm_diags_1606894934352/_test_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_place/lib/python3.9/site-packages/acme_diags/driver/qbo_driver.py:129: RuntimeWarning: divide by zero encountered in true_divide
  period0 = 1 / frequency0
/home/conda/feedstock_root/build_artifacts/e3sm_diags_1606894934352/_test_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_place/lib/python3.9/site-packages/acme_diags/driver/qbo_driver.py:137: RuntimeWarning: invalid value encountered in multiply
  Pxf0 = period_end0 * np.sum(psd_x0)
/home/conda/feedstock_root/build_artifacts/e3sm_diags_1606894934352/_test_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_place/lib/python3.9/site-packages/acme_diags/plot/cartopy/qbo_plot.py:97: UserWarning: This figure includes Axes that are not compatible with tight_layout, so results might be incorrect.
  plt.tight_layout()
Traceback (most recent call last):
  File "/home/conda/feedstock_root/build_artifacts/e3sm_diags_1606894934352/_test_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_place/lib/python3.9/site-packages/acme_diags/acme_diags_driver.py", line 275, in run_diag
    single_result = module.run_diag(parameters)
  File "/home/conda/feedstock_root/build_artifacts/e3sm_diags_1606894934352/_test_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_place/lib/python3.9/site-packages/acme_diags/driver/streamflow_driver.py", line 95, in run_diag
    gauges_path = '/{}/GSIM/GSIM_catchment_characteristics_all_1km2.csv'.format(parameter.reference_data_path.strip('/'))
AttributeError: 'StreamflowParameter' object has no attribute 'reference_data_path'
No handles with labels found to put in legend.
TestAllSets.results_dir=all_sets_results_test/
............all_sets_results_test/qbo/qbo-test/qbo_diags.png
..F..
======================================================================
FAIL: test_streamflow (test_diags.TestAllSets)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/conda/feedstock_root/build_artifacts/e3sm_diags_1606894934352/test_tmp/tests/system/test_diags.py", line 265, in test_streamflow
    self.check_streamflow_plots()
  File "/home/conda/feedstock_root/build_artifacts/e3sm_diags_1606894934352/test_tmp/tests/system/test_diags.py", line 174, in check_streamflow_plots
    self.assertTrue(os.path.exists(full_png_path))
AssertionError: False is not true
```

**Comment by xylar** [comment]
I am disabling this test for the 2.3.0 release on conda-forge but I think it might point to a problem that will need to be addressed.

**Comment by forsyth2** [comment]
This is because `tests/system/all_sets.cfg` (https://github.com/E3SM-Project/e3sm_diags/blob/master/tests/system/all_sets.cfg#L286) doesn't specify `parameter.reference_data_path`. This will be resolved when we move the test data to a common server (#303, #306). I'm planning to complete that before the next E3SM Diags release (i.e. v2.4.0).

**Comment by chengzhuzhang** [comment]
@forsyth2 exactly! I am typing the same thing:)

**Comment by zshaheen** [comment]
We were pretty lazy when it came to this sadly, but fixing up the CI (Travis CI and CircleCI) would be a good idea.

Travis CI was for testing on Linux, while Circle CI was for macOS. I'm pretty sure macOS testing isn't needed anymore. 

Also, I'd look into [Github Actions](https://github.blog/2019-08-08-github-actions-now-supports-ci-cd/) and you'd might want to think of using that instead of the third-party Travis CI.

**Comment by xylar** [comment]
@chengzhuzhang and @forsyth2, I recently had trouble with Travis CI on our various MPAS repos and I switched to Azure Pipelines.  If you'd like to make that change, I would be willing to help you get started.  It is a lot faster and supports a lot more simultaneous tests.  It is the preferred CI for `conda-forge` feedstocks.  It would support both Linux and OSX (we always test both).

**Comment by chengzhuzhang** [comment]
Streamflow test failed in unit tests. It appears the path for gauge .csv file is not set up correctly.

Error in acme_diags.driver.streamflow_driver
Traceback (most recent call last):
  File "/Users/zhang40/miniconda3/envs/dev_dec2_2020_py3.8/lib/python3.8/site-packages/acme_diags/acme_diags_driver.py", line 275, in run_diag
    single_result = module.run_diag(parameters)
  File "/Users/zhang40/miniconda3/envs/dev_dec2_2020_py3.8/lib/python3.8/site-packages/acme_diags/driver/streamflow_driver.py", line 100, in run_diag
    with open(gauges_path) as gauges_file:
FileNotFoundError: [Errno 2] No such file or directory: '/../unit_test_data/GSIM/GSIM_catchment_characteristics_all_1km2.csv'
