### ISSUE TITLE
Allow QBO Diags to work with insufficient ref data

### ISSUE THREAD

**Issue by forsyth2** [E3SM-Project/e3sm_diags#412]
Currently, QBO diags doesn't work if the ref data and test data aren't for the same amount of time. For instance, on https://github.com/E3SM-Project/zppy/pull/2 when 50 years of test data are used, QBO diags fail because there is only 38 years of ref data. We could simply allow the ref data line to end earlier than the test data line in the bottom plot.

**Comment by forsyth2** [comment]
Error on https://github.com/E3SM-Project/zppy/pull/2 using 38 years of ref data but 50 years of test data:
```
Traceback (most recent call last):
  File "/lcrc/soft/climate/e3sm-unified/base/envs/e3sm_unified_1.4.0/lib/python3.7/site-packages/acme_diags/acme_diags_driver.py", line 275, in run_diag
    single_result = module.run_diag(parameters)
  File "/lcrc/soft/climate/e3sm-unified/base/envs/e3sm_unified_1.4.0/lib/python3.7/site-packages/acme_diags/driver/qbo_driver.py", line 245, in run_diag
    plot(period_new, parameter, test, ref)
  File "/lcrc/soft/climate/e3sm-unified/base/envs/e3sm_unified_1.4.0/lib/python3.7/site-packages/acme_diags/plot/cartopy/qbo_plot.py", line 74, in plot
    plot_colors=cmap2, color_levels=color_levels0, color_ticks=[-50, -25, -5, 5, 25, 50])
  File "/lcrc/soft/climate/e3sm-unified/base/envs/e3sm_unified_1.4.0/lib/python3.7/site-packages/acme_diags/plot/cartopy/qbo_plot.py", line 31, in plot_panel
    p1 = ax.contourf(x['data'], y['data'], z['data'], color_levels, cmap=plot_colors)
  File "/lcrc/soft/climate/e3sm-unified/base/envs/e3sm_unified_1.4.0/lib/python3.7/site-packages/matplotlib/__init__.py", line 1447, in inner
    return func(ax, *map(sanitize_sequence, args), **kwargs)
  File "/lcrc/soft/climate/e3sm-unified/base/envs/e3sm_unified_1.4.0/lib/python3.7/site-packages/matplotlib/axes/_axes.py", line 6335, in contourf
    contours = mcontour.QuadContourSet(self, *args, **kwargs)
  File "/lcrc/soft/climate/e3sm-unified/base/envs/e3sm_unified_1.4.0/lib/python3.7/site-packages/matplotlib/contour.py", line 816, in __init__
    kwargs = self._process_args(*args, **kwargs)
  File "/lcrc/soft/climate/e3sm-unified/base/envs/e3sm_unified_1.4.0/lib/python3.7/site-packages/matplotlib/contour.py", line 1430, in _process_args
    x, y, z = self._contour_args(args, kwargs)
  File "/lcrc/soft/climate/e3sm-unified/base/envs/e3sm_unified_1.4.0/lib/python3.7/site-packages/matplotlib/contour.py", line 1488, in _contour_args
    x, y, z = self._check_xyz(args[:3], kwargs)
  File "/lcrc/soft/climate/e3sm-unified/base/envs/e3sm_unified_1.4.0/lib/python3.7/site-packages/matplotlib/contour.py", line 1541, in _check_xyz
    f"Shapes of x {x.shape} and z {z.shape} do not match")
TypeError: Shapes of x (72, 456) and z (72, 600) do not match
```

**Comment by chengzhuzhang** [comment]
@forsyth2  yes, this is expected. I think one option could be for QBO year boundaries:
- If test peiod great than a threshold (i.e., 38 years) take the first 38 years and do QBO analysis. 
@golaz do you think it should work okay?
