### ISSUE TITLE
Test during installation not available

### ISSUE THREAD

**Issue by xylar** [E3SM-Project/e3sm_diags#503]
Following the instructions for the development environment, the following step doesn't work:
```
8. Run a quick test which generates one of each plot type.

    ::

        cd tests/system
        python all_sets.py -d all_sets.cfg
```
The `system` directory isn't there.  I tried using the `integration` directory but I see:
```
$ python all_sets.py -d all_sets.cfg 
[]
[]
[]
[]
You have no value for ref_names. Caculate test data only
Saved environment yml file to: all_sets_results_test/prov/environment.yml
Saved command used to: all_sets_results_test/prov/cmd_used.txt
Saved cfg file to: all_sets_results_test/prov/all_sets.cfg
Saved Python script to: all_sets_results_test/prov/all_sets.py
Variable: T
Error in e3sm_diags.driver.zonal_mean_xy_driver
Traceback (most recent call last):
  File "/home/ac.xylar/chrysalis/miniconda3/envs/e3sm_diags_env_dev/lib/python3.9/site-packages/e3sm_diags/e3sm_diags_driver.py", line 277, in run_diag
    single_result = module.run_diag(parameters)  # type: ignore
  File "/home/ac.xylar/chrysalis/miniconda3/envs/e3sm_diags_env_dev/lib/python3.9/site-packages/e3sm_diags/driver/zonal_mean_xy_driver.py", line 112, in run_diag
    mv1 = test_data.get_climo_variable(var, season)
  File "/home/ac.xylar/chrysalis/miniconda3/envs/e3sm_diags_env_dev/lib/python3.9/site-packages/e3sm_diags/driver/utils/dataset.py", line 159, in get_climo_variable
    filename = self.get_test_filename_climo(season)
  File "/home/ac.xylar/chrysalis/miniconda3/envs/e3sm_diags_env_dev/lib/python3.9/site-packages/e3sm_diags/driver/utils/dataset.py", line 267, in get_test_filename_climo
    raise IOError("File not found: {}".format(fnm))
OSError: File not found: integration_test_data/T_20161118.beta0.FC5COSP.ne30_ne30.edison_ANN_climo.nc
```
It seems like this step needs to be removed or fixed.

**Comment by chengzhuzhang** [comment]
@forsyth2 it looks like related to the recent testing update. Would you please look into it?

**Comment by forsyth2** [comment]
@chengzhuzhang Yes, it's because #476 removed the `system` directory. I will update the docs. Considering this only affects developers, I don't think we need to edit the v2.5.0 docs (i.e., editing only the `master` docs is sufficient).

**Comment by forsyth2** [comment]
> `OSError: File not found: integration_test_data/T_20161118.beta0.FC5COSP.ne30_ne30.edison_ANN_climo.nc`

This is because the data hasn't been downloaded. This is done automatically when the whole test suite is run though. See #508.
