### ISSUE TITLE
FileNotFoundError for e3sm_diags_run.log when having multiple runs

### ISSUE THREAD

**Issue by chengzhuzhang** [E3SM-Project/e3sm_diags#601]
When running e3sm_diags using Python API to loop through a number of runs. I hit following error, not sure if adding a time stamp to the file name of `e3sm_diags_run.log' would help? Also I notice that, some log info often repeat for twice, not sure what could cause this. @tomvothecoder would you please look at this issue when you have a chance? Thanks!
```
2022-06-23 12:42:53,034 [INFO]: logger.py(move_log_to_prov_dir:91) >> Log file saved in /var/www/acme/acme-diags/zhang40/CAM6-NTF_exp2a/prov/e3sm_diags_run.log
2022-06-23 12:42:53,034 [INFO]: logger.py(move_log_to_prov_dir:91) >> Log file saved in /var/www/acme/acme-diags/zhang40/CAM6-NTF_exp2a/prov/e3sm_diags_run.log
Traceback (most recent call last):
  File "/home/zhang40/miniconda3/envs/edv260/lib/python3.9/shutil.py", line 806, in move
    os.rename(src, real_dst)
OSError: [Errno 18] Invalid cross-device link: 'e3sm_diags_run.log' -> '/var/www/acme/acme-diags/zhang40/CAM6-NTF_exp2a/prov/e3sm_diags_run.log'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/zhang40/e3sm_diags_parameters/run_diurnal_cycle.py", line 27, in <module>
    runner.run_diags([param,param_dc])
  File "/home/zhang40/miniconda3/envs/edv260/lib/python3.9/site-packages/e3sm_diags/run.py", line 37, in run_diags
    move_log_to_prov_dir(final_params[0].results_dir)
  File "/home/zhang40/miniconda3/envs/edv260/lib/python3.9/site-packages/e3sm_diags/logger.py", line 93, in move_log_to_prov_dir
    shutil.move(LOG_FILENAME, provenance_dir)
  File "/home/zhang40/miniconda3/envs/edv260/lib/python3.9/shutil.py", line 826, in move
    copy_function(src, real_dst)
  File "/home/zhang40/miniconda3/envs/edv260/lib/python3.9/shutil.py", line 435, in copy2
    copyfile(src, dst, follow_symlinks=follow_symlinks)
  File "/home/zhang40/miniconda3/envs/edv260/lib/python3.9/shutil.py", line 264, in copyfile
    with open(src, 'rb') as fsrc, open(dst, 'wb') as fdst:
FileNotFoundError: [Errno 2] No such file or directory: 'e3sm_diags_run.log'
```

**Comment by tomvothecoder** [comment]
Sure, this might be useful for later reference.
https://stackoverflow.com/questions/42392600/oserror-errno-18-invalid-cross-device-link

> I think rename only works when the source and target names are on the same file system. You probably have different mounts. Otherwise you get that error. You can implement the same effect with a copy and a delete.
> 
> Hope it helps

I'll need the script you used and the name of the machine to reproduce the traceback.

**Comment by chengzhuzhang** [comment]
@tomvothecoder Hey Tom, here is the run script that you could try to reproduce the problem on ACME1 using e3sm_diags master branch. This script loops over multiple experiments. I also see the same error when running e3sm_diags looping over all the CMIP experiments.


```
import os
from e3sm_diags.parameter.core_parameter import CoreParameter
from e3sm_diags.parameter.diurnal_cycle_parameter import DiurnalCycleParameter
from e3sm_diags.run import runner

param = CoreParameter()

test_names = ['CAM6-CTL_exp2a','CAM6-NTF_exp2a','CMCGEM_exp2a','ECMWF_exp2a', 'LLNLE3SM_exp2a', 'LLNLE3SM_notrigger_exp2a','TaiESM_exp2a', 'UMGA7_exp2a','UMGA8_exp2a']
#test_names = ['CMCGEM_exp2a']
#test_names = ['UMGA8_exp2a_pr']
for test_name in test_names:
    #param.reference_data_path = '/home/zhang40/tests/TRMM_1.5hour_shift'
    param.reference_data_path = '/p/user_pub/e3sm/e3sm_diags_data/obs_for_e3sm_diags/climatology'
    param.test_data_path = '/p/user_pub/e3sm/tao4/'
    param.test_name = test_name
    param.short_test_name = test_name.split('_')[0]
    param.seasons = ["ANN", "JJA"]   #all seasons ["ANN","DJF", "MAM", "JJA", "SON"] will run,if comment out"

    prefix = '/var/www/acme/acme-diags/zhang40/tests'
    param.results_dir = os.path.join(prefix, test_name+'_new')
    param.multiprocessing = True
    param.num_workers = 24

    param_dc = DiurnalCycleParameter()

    # Use below to run all core sets of diags:
    #runner.sets_to_run = ['lat_lon','zonal_mean_xy', 'zonal_mean_2d', 'polar', 'cosp_histogram', 'meridional_mean_2d']
    runner.sets_to_run = ['diurnal_cycle']
    runner.run_diags([param,param_dc])
```
